version: '3.8'

services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    env_file:
      - .docker.env
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - admin_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  admin_backend:
    build: .
    container_name: admin_backend
    networks:
      - admin_network
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./app/:/app/app/

  admin_frontend:
    build: ./ui
    container_name: admin_frontend
    networks:
      - admin_network
    volumes:
      - ./ui/src/:/app/src/

  nginx:
    image: nginx:1.25.3
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - admin_backend
      - admin_frontend
    networks:
      - admin_network

networks:
  admin_network:
    driver: bridge
